fix(STADTPULS-732): Fix requests failing because of sorting of inexistant records
technologiestiftung/stadtpuls-frontend pull request #281
Opened 2022-03-23 14:43 UTC by vogelino

This PR fixes the following type of errors, which are responsible for the incapacity of users to create sensor or to see the sensors in the home page:
```json
{
  message: "Cannot apply filter because 'records' is not an embedded resource in this request",
  hint: "Verify that 'records' is included in the 'select' query parameter."
}
```

The problem was that we are not querying the records in the sensors queries, but are still including sorting of records in the query. At the time this was done, no error was triggered. It seems supabase changed this and now throw errors. 

**PS:** The GitHub Action "Prevent merge from non-staging to main" will fail, as I am comparing this branch directly to main. In this case this is intended as it is a quickfix. Ignore the failing check.

2022-03-23 14:54 UTC, ff6347 requested changes
PR should go against staging and the tests are broken and github is having issues as well

2022-03-23 14:57 UTC, vogelino commented
> PR should go against staging and the tests are broken and github is having issues as well

As stated in the description of the PR 👆, as this is a quickfix, it compares to main and not to staging. Otherwise other changes made to staging would also be merged into main. The only tests failing are the snapshots, which I generated using the wrong .env file. I just fixed it and am waiting for the action to run once again.

2022-03-23 15:00 UTC, ff6347 commented
> > PR should go against staging and the tests are broken and github is having issues as well
> 
> As stated in the description of the PR 👆, as this is a quickfix, it compares to main and not to staging. Otherwise other changes made to staging would also be merged into main. The only tests failing are the snapshots, which I generated using the wrong .env file. I just fixed it and am waiting for the action to run once again.

Sorry. Those who read have a great advantage.

2022-03-23 15:01 UTC, ff6347 approved these changes
LGTM. 🚀

2022-03-23 15:29 UTC, dnsos approved these changes
Good work!

I'm not encountering this bug anymore when viewing or creating sensors (Deploy Preview environment). Curious that the error handling changed under the radar for us 😕

2022-03-23 15:31 UTC, merged

2022-03-29 12:00 UTC, tsboter commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/technologiestiftung/stadtpuls-frontend/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: